In [60]:
import numpy as np

In [61]:
a = np.arange(15)

In [62]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [63]:
type(a)

numpy.ndarray

In [64]:
a.ndim

1

In [65]:
a.shape

(15,)

In [66]:
a = a.reshape(3,5)

In [67]:
A = np.ones((2,5))

In [68]:
A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [69]:
b = a.reshape(3,5)

In [70]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [71]:
b.ndim

2

In [72]:
np.arange(2,6,2)

array([2, 4])

In [73]:
s = np.arange(2,3,0.1).reshape(1,10)

In [74]:
s

array([[2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9]])

In [75]:
s.ndim

2

In [76]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [77]:
type(b)

numpy.ndarray

In [78]:
b.dtype

dtype('int32')

In [79]:
p = np.array([2,3,4,5,6])
p.shape

(5,)

In [80]:
p.size

5

In [81]:
p.ndim

1

In [82]:
a = np.arange(15)

In [83]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [84]:
p = np.arange(10)

In [85]:
p

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
p = np.arange(10)

In [87]:
p

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
from numpy import pi

In [89]:
p = np.linspace(0,pi*0.1,100)

In [90]:
p

array([0.        , 0.00317333, 0.00634665, 0.00951998, 0.0126933 ,
       0.01586663, 0.01903996, 0.02221328, 0.02538661, 0.02855993,
       0.03173326, 0.03490659, 0.03807991, 0.04125324, 0.04442656,
       0.04759989, 0.05077321, 0.05394654, 0.05711987, 0.06029319,
       0.06346652, 0.06663984, 0.06981317, 0.0729865 , 0.07615982,
       0.07933315, 0.08250647, 0.0856798 , 0.08885313, 0.09202645,
       0.09519978, 0.0983731 , 0.10154643, 0.10471976, 0.10789308,
       0.11106641, 0.11423973, 0.11741306, 0.12058638, 0.12375971,
       0.12693304, 0.13010636, 0.13327969, 0.13645301, 0.13962634,
       0.14279967, 0.14597299, 0.14914632, 0.15231964, 0.15549297,
       0.1586663 , 0.16183962, 0.16501295, 0.16818627, 0.1713596 ,
       0.17453293, 0.17770625, 0.18087958, 0.1840529 , 0.18722623,
       0.19039955, 0.19357288, 0.19674621, 0.19991953, 0.20309286,
       0.20626618, 0.20943951, 0.21261284, 0.21578616, 0.21895949,
       0.22213281, 0.22530614, 0.22847947, 0.23165279, 0.23482

In [91]:
np.linspace(7,8,10)

array([7.        , 7.11111111, 7.22222222, 7.33333333, 7.44444444,
       7.55555556, 7.66666667, 7.77777778, 7.88888889, 8.        ])

In [92]:
p.shape

(100,)

In [93]:
p.reshape(25,4)

array([[0.        , 0.00317333, 0.00634665, 0.00951998],
       [0.0126933 , 0.01586663, 0.01903996, 0.02221328],
       [0.02538661, 0.02855993, 0.03173326, 0.03490659],
       [0.03807991, 0.04125324, 0.04442656, 0.04759989],
       [0.05077321, 0.05394654, 0.05711987, 0.06029319],
       [0.06346652, 0.06663984, 0.06981317, 0.0729865 ],
       [0.07615982, 0.07933315, 0.08250647, 0.0856798 ],
       [0.08885313, 0.09202645, 0.09519978, 0.0983731 ],
       [0.10154643, 0.10471976, 0.10789308, 0.11106641],
       [0.11423973, 0.11741306, 0.12058638, 0.12375971],
       [0.12693304, 0.13010636, 0.13327969, 0.13645301],
       [0.13962634, 0.14279967, 0.14597299, 0.14914632],
       [0.15231964, 0.15549297, 0.1586663 , 0.16183962],
       [0.16501295, 0.16818627, 0.1713596 , 0.17453293],
       [0.17770625, 0.18087958, 0.1840529 , 0.18722623],
       [0.19039955, 0.19357288, 0.19674621, 0.19991953],
       [0.20309286, 0.20626618, 0.20943951, 0.21261284],
       [0.21578616, 0.21895949,

In [94]:
p.ndim

1

In [95]:
p

array([0.        , 0.00317333, 0.00634665, 0.00951998, 0.0126933 ,
       0.01586663, 0.01903996, 0.02221328, 0.02538661, 0.02855993,
       0.03173326, 0.03490659, 0.03807991, 0.04125324, 0.04442656,
       0.04759989, 0.05077321, 0.05394654, 0.05711987, 0.06029319,
       0.06346652, 0.06663984, 0.06981317, 0.0729865 , 0.07615982,
       0.07933315, 0.08250647, 0.0856798 , 0.08885313, 0.09202645,
       0.09519978, 0.0983731 , 0.10154643, 0.10471976, 0.10789308,
       0.11106641, 0.11423973, 0.11741306, 0.12058638, 0.12375971,
       0.12693304, 0.13010636, 0.13327969, 0.13645301, 0.13962634,
       0.14279967, 0.14597299, 0.14914632, 0.15231964, 0.15549297,
       0.1586663 , 0.16183962, 0.16501295, 0.16818627, 0.1713596 ,
       0.17453293, 0.17770625, 0.18087958, 0.1840529 , 0.18722623,
       0.19039955, 0.19357288, 0.19674621, 0.19991953, 0.20309286,
       0.20626618, 0.20943951, 0.21261284, 0.21578616, 0.21895949,
       0.22213281, 0.22530614, 0.22847947, 0.23165279, 0.23482

In [96]:
f = np.sin(p)

In [97]:
f

array([0.        , 0.00317332, 0.00634661, 0.00951983, 0.01269296,
       0.01586596, 0.01903881, 0.02221145, 0.02538388, 0.02855605,
       0.03172793, 0.0348995 , 0.03807071, 0.04124154, 0.04441195,
       0.04758192, 0.0507514 , 0.05392038, 0.05708881, 0.06025667,
       0.06342392, 0.06659053, 0.06975647, 0.07292171, 0.07608622,
       0.07924996, 0.0824129 , 0.08557501, 0.08873626, 0.09189661,
       0.09505604, 0.09821452, 0.101372  , 0.10452846, 0.10768387,
       0.1108382 , 0.11399141, 0.11714347, 0.12029435, 0.12344403,
       0.12659245, 0.12973961, 0.13288545, 0.13602996, 0.1391731 ,
       0.14231484, 0.14545514, 0.14859398, 0.15173133, 0.15486714,
       0.1580014 , 0.16113406, 0.1642651 , 0.16739449, 0.17052219,
       0.17364818, 0.17677241, 0.17989487, 0.18301552, 0.18613432,
       0.18925124, 0.19236627, 0.19547935, 0.19859047, 0.20169958,
       0.20480667, 0.20791169, 0.21101462, 0.21411542, 0.21721407,
       0.22031053, 0.22340477, 0.22649677, 0.22958648, 0.23267

In [98]:
d = np.arange(20).reshape(4,5)

In [99]:
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [100]:
d[3][4]

19

In [101]:
d.ndim

2

In [102]:
b = np.array([(1,2,3,4),(5,6,7,8)],dtype = complex)
b

array([[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j]])

In [103]:
b.reshape(8,1)

array([[1.+0.j],
       [2.+0.j],
       [3.+0.j],
       [4.+0.j],
       [5.+0.j],
       [6.+0.j],
       [7.+0.j],
       [8.+0.j]])

In [104]:
b.ndim

2

In [105]:
np.ones((10,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [106]:
s = np.arange(21).reshape(7,3,1)

In [107]:
s

array([[[ 0],
        [ 1],
        [ 2]],

       [[ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14]],

       [[15],
        [16],
        [17]],

       [[18],
        [19],
        [20]]])

In [108]:
s.ndim

3

In [109]:
type(s)

numpy.ndarray

In [110]:
a = np.array([20,30,40,50])
b = np.arange(4)

In [111]:
a + b

array([20, 31, 42, 53])

In [112]:
a*b

array([  0,  30,  80, 150])

In [113]:
a**b

array([     1,     30,   1600, 125000], dtype=int32)

In [114]:
a - b

array([20, 29, 38, 47])

In [115]:
a % b

C:\Users\Devendra Pathak\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in remainder
  """Entry point for launching an IPython kernel.


array([0, 0, 0, 2], dtype=int32)

In [116]:
a // b

C:\Users\Devendra Pathak\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


array([ 0, 30, 20, 16], dtype=int32)

In [117]:
a / b

C:\Users\Devendra Pathak\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf, 30.        , 20.        , 16.66666667])

In [118]:
a**2

array([ 400,  900, 1600, 2500], dtype=int32)

In [119]:
a + 2

array([22, 32, 42, 52])

In [120]:
a = np.array([[1,1],[0,1]])
b = np.array([[2,0],[3,4]])

In [121]:
a

array([[1, 1],
       [0, 1]])

In [122]:
b

array([[2, 0],
       [3, 4]])

In [123]:
a +b

array([[3, 1],
       [3, 5]])

In [124]:
a- b

array([[-1,  1],
       [-3, -3]])

In [125]:
a*b

array([[2, 0],
       [0, 4]])

In [126]:
a%b

C:\Users\Devendra Pathak\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in remainder
  """Entry point for launching an IPython kernel.


array([[1, 0],
       [0, 1]], dtype=int32)

In [127]:
a/b

C:\Users\Devendra Pathak\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[0.5 ,  inf],
       [0.  , 0.25]])

In [128]:
a//b

C:\Users\Devendra Pathak\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


array([[0, 0],
       [0, 0]], dtype=int32)

In [129]:
a**2

array([[1, 1],
       [0, 1]], dtype=int32)

In [130]:
a<10

array([[ True,  True],
       [ True,  True]])

In [131]:
b>10

array([[False, False],
       [False, False]])

In [132]:
a@b

array([[5, 4],
       [3, 4]])

In [133]:
a.dot(b)

array([[5, 4],
       [3, 4]])

In [134]:
a = np.arange(12).reshape(4,3)

In [135]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [136]:
a.sum(axis = 0)

array([18, 22, 26])

In [137]:
a.sum(axis=1)

array([ 3, 12, 21, 30])

In [138]:
a.min(axis = 0)

array([0, 1, 2])

In [139]:
a.max(axis =1)

array([ 2,  5,  8, 11])

In [140]:
b = np.array([1,2,3,4],ndmin = 5)

In [141]:
b.ndim

5

In [142]:
b = np.array([(1,2,3,4,5),(2.4,3,4,6,7)]) 

In [143]:
b

array([[1. , 2. , 3. , 4. , 5. ],
       [2.4, 3. , 4. , 6. , 7. ]])

In [144]:
type(b)

numpy.ndarray

In [145]:
a = np.ones( (3,4) )  

In [146]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [147]:
type(a[0,0])

numpy.float64

In [148]:
d = np.array([6,7,8]) 

In [149]:
d

array([6, 7, 8])

In [150]:
d.fill(3) 

In [151]:
d

array([3, 3, 3])

In [152]:
a = np.ones( (2,3,4,5))  

In [153]:
a

array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]])

In [154]:
a.fill(7)

In [155]:
a

array([[[[7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.]],

        [[7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.]],

        [[7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.]]],


       [[[7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.]],

        [[7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.]],

        [[7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.],
         [7., 7., 7., 7., 7.]]]])

In [156]:
a.ndim

4

In [157]:
c = np.ones((2,3))

In [158]:
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [159]:
c.ndim

2

In [160]:
c = np.matrix(c)

In [161]:
c

matrix([[1., 1., 1.],
        [1., 1., 1.]])

In [162]:
c[0]

matrix([[1., 1., 1.]])

In [163]:
a = np.arange(0,2,0.3) 

In [164]:
a

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [165]:
a = np.arange(120).reshape(2,3,4,5)  

In [166]:
a     

array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]]],


       [[[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])

In [167]:
a.ndim

4

In [168]:
a.shape

(2, 3, 4, 5)

In [169]:
a = np.array( [20,30,40,50] ) 
b = np.arange(1,5)

In [170]:
a + b

array([21, 32, 43, 54])

In [171]:
a - b

array([19, 28, 37, 46])

In [172]:
b = np.random.random((2,3))

In [173]:
b

array([[0.00389299, 0.18784081, 0.89844015],
       [0.59466741, 0.23229083, 0.77241712]])

In [174]:
b.sum()

2.6895493106270645

In [175]:
b.min()

0.0038929928045695616

In [176]:
n = np.arange(12).reshape(4,3)

In [177]:
n

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [178]:
n.sum(axis = 0)

array([18, 22, 26])

In [179]:
n.min(axis = 1)

array([0, 3, 6, 9])

In [180]:
n.cumsum(axis = 0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15],
       [18, 22, 26]], dtype=int32)

In [181]:
a = np.arange(12).reshape(3,4) 

In [182]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [183]:
a = np.matrix(a)

In [184]:
a

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [185]:
type(a)

numpy.matrix

In [186]:
b = np.arange(16).reshape(2,4,1,2)

In [187]:
b

array([[[[ 0,  1]],

        [[ 2,  3]],

        [[ 4,  5]],

        [[ 6,  7]]],


       [[[ 8,  9]],

        [[10, 11]],

        [[12, 13]],

        [[14, 15]]]])

In [188]:
np.ravel(b)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [189]:
a = np.array([[1,1],[0,1]])
b = np.array([[2,0],[3,4]])

In [190]:
a

array([[1, 1],
       [0, 1]])

In [191]:
b

array([[2, 0],
       [3, 4]])

In [192]:
A = np.matrix(a)
B = np.matrix(b)

In [193]:
A

matrix([[1, 1],
        [0, 1]])

In [194]:
B

matrix([[2, 0],
        [3, 4]])

In [195]:
np.multiply(A,B)

matrix([[2, 0],
        [0, 4]])

In [196]:
type(A)

numpy.matrix

In [197]:
A.ndim

2

In [198]:
c = np.ravel(A)

In [199]:
c

array([1, 1, 0, 1])

In [200]:
type(c)

numpy.ndarray

In [201]:
c.ndim

1

In [202]:
c = np.ravel(B)

In [203]:
c

array([2, 0, 3, 4])

In [204]:
A.T

matrix([[1, 0],
        [1, 1]])

In [205]:
b = np.array(B)

In [206]:
b

array([[2, 0],
       [3, 4]])

In [207]:
np.power(A,3)

matrix([[1, 1],
        [0, 1]], dtype=int32)

In [208]:
np.power(B,3)

matrix([[ 8,  0],
        [27, 64]], dtype=int32)

In [209]:
B.size

4

In [210]:
B.shape

(2, 2)

In [211]:
np.random.randn(1,10)

array([[ 0.34621583,  0.7444392 ,  0.41066623,  1.25730965,  2.28354651,
         0.37102473,  0.79949138,  0.21932363, -0.72400396, -0.11304384]])