In [1]:
from sklearn.naive_bayes import GaussianNB
import numpy as np
from scipy.io import loadmat

In [5]:
spam_train = loadmat("C:\spamTrain.mat")
spam_test = loadmat("C:\spamTest.mat")
X = spam_train['X']
Xtest = spam_test['Xtest']
y = spam_train['y'].ravel()
ytest = spam_test['ytest'].ravel()

In [6]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [7]:
X.shape

(4000, 1899)

In [8]:
gnb = GaussianNB()

In [9]:
gnb.fit(X,y)

GaussianNB(priors=None, var_smoothing=1e-09)

In [14]:
np.unique(X)

array([0, 1], dtype=uint8)

In [10]:
np.unique(y)

array([0, 1], dtype=uint8)

In [12]:
gnb.score(Xtest,ytest)

0.872

In [13]:
gnb.score(X,y)

0.85425

In [15]:
from sklearn.naive_bayes import MultinomialNB

In [17]:
mnb = MultinomialNB()

In [18]:
mnb.fit(X,y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [19]:
mnb.score(Xtest,ytest)

0.973

In [20]:
mnb.score(X,y)

0.972

In [21]:
from sklearn.naive_bayes import BernoulliNB

In [23]:
bnb = BernoulliNB()

In [24]:
bnb.fit(X,y)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [25]:
bnb.score(Xtest,ytest)

0.948

In [26]:
bnb.score(X,y)

0.95125